# Generated by Django 5.2.6 on 2025-09-30 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AromaFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('citrus', 'Citrus/Fresh'), ('floral', 'Floral'), ('herbal', 'Herbal/Green'), ('woody', 'Woody/Earthy'), ('spicy', 'Spicy/Warm'), ('resin', 'Resin/Balsamic'), ('minty', 'Camphoraceous/Minty')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('base', 'Base')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('relaxation', 'Relaxation / Calming / Stress Relief'), ('uplifting', 'Uplifting / Energizing / Mood Boost'), ('grounding', 'Grounding / Centering / Meditative'), ('invigorating', 'Invigorating / Stimulating / Refreshing'), ('soothing', 'Soothing / Comforting / Emotional Support'), ('respiratory', 'Respiratory / Clearing / Sinus Support'), ('sleep', 'Sleep / Sedative'), ('focus', 'Focus / Concentration / Mental Clarity'), ('immune', 'Immune Support / Cleansing / Antimicrobial'), ('aphrodisiac', 'Aphrodisiac / Sensual / Romantic')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EssentialOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name must contain only capitalized English words separated by single spaces.', regex='^[A-Z][a-z]*( [A-Z][a-z]*)*$')])),
                ('aromas', models.ManyToManyField(blank=True, to='api.aromafamily')),
                ('notes', models.ManyToManyField(blank=True, to='api.notetype')),
                ('vibes', models.ManyToManyField(blank=True, to='api.vibe')),
            ],
        ),
        migrations.CreateModel(
            name='BlendIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drops', models.PositiveIntegerField(default=1)),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blend')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.essentialoil')),
            ],
            options={
                'unique_together': {('blend', 'oil')},
            },
        ),
        migrations.AddField(
            model_name='blend',
            name='oils',
            field=models.ManyToManyField(through='api.BlendIngredient', to='api.essentialoil'),
        ),
    ]
