# Generated by Django 5.2.6 on 2025-10-12 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If false, only the creator can see this blend.'),
        ),
        migrations.AlterField(
            model_name='essentialoil',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name must start with a capitalized word, subsequent words (including after a comma) can start with uppercase or lowercase letters, and may optionally end with a parenthetical (no nested parentheses).', regex='^[A-Z][a-z]*( [A-Za-z]+)*(, [A-Za-z]+)?( \\([A-Za-z ]+\\))?$')]),
        ),
    ]
