# Generated by Django 5.2.6 on 2025-10-19 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_useroilrelation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useroilrelation',
            new_name='api_useroil_user_id_2be2c4_idx',
            old_name='api_useroil_user_id__5afb66_idx',
        ),
        migrations.AddField(
            model_name='blendingredient',
            name='note',
            field=models.ForeignKey(blank=True, help_text='Chosen note (top/middle/base) for this oil in the blend.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_ingredients', to='api.notetype'),
        ),
    ]
