# Generated by Django 5.2.6 on 2026-01-05 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_api_useroil_user_id__5afb66_idx_api_useroil_user_id_2be2c4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlendFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.blend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='api_userble_user_id_508cbe_idx'), models.Index(fields=['blend'], name='api_userble_blend_i_363097_idx')],
                'unique_together': {('user', 'blend')},
            },
        ),
    ]
